cdjcy:
  errorcodes:
    #系统管理错误码
    #用户管理错误码 1001-1020
    -1001: "用户信息不存在"
    -1002: "用户信息添加失败"
    -1003: "用户信息修改失败"
    -1004: "用户信息删除失败"
    -999: "未登录"
    #role角色管理错误码 1021 - 1040
    -1021: "角色信息不存在"
    -1022: "修改角色信息出现错误，请检查需要修改信息"
    -1023: "添加角色出现错误，请检查添加修改信息"
    -1024: "不能删除角色信息,存在该角色的用户"
    -1025: "删除角色出现错误"
    -1026: "不能不能批量删除角色信息，存在角色用户"
    -1027: "批量删除角色出现错误"

    #案件管理错误码 1101-1110
    -1101: "不存在该案件"
    -1102: "绑定办案对象失败"
    -1103: "解绑办案对象失败"
    -1105: "案件绑定人员（办案或指挥或授权）失败"
    -1106: "案件列表加载失败"
    -1107: "根据id查找案件失败"
    -1108: "案件删除失败"
    -1110: "案件添加失败"
    -1116: "查询登录用户关联案件失败"
    -1117: "查询关联犯人列表失败"
    -1118: "查询关联犯人列表的案件不存在"

    #办案对象错误码 1111-1120
    -1111: "办案对象添加失败"
    -1112: "办案对象删除失败"
    -1113: "办案对象修改失败"
    -1114: "办案对象查找失败"

    #文件信息错误码 1121-1130
    -1121: "文件信息添加失败"
    -1122: "文件信息修改失败"
    -1123: "文件信息删除失败"
    -1124: "根据id查找文件信息失败"

    #权限字典错误码 1041-1060

    #分类错误码 -1200-1220
    -1201: "查询分类失败"
    -1202: "修改分类失败"
    -1203: "新增分类失败"
    -1204: "删除分类失败"
    #设备管理错误码
    -1301: "查找单元列表失败"
    -1302: "新增区域失败"
    -1303: "删除区域失败"
    -1304: "更新区域失败"
    -1305: "根据Id查询区域"
    -1306: "查找房间列表失败"
    -1307: "新增房间失败"
    -1308: "删除房间失败"
    -1309: "更新房间失败"
    -1310: "根据Id查询房间失败"
    -1311: "查找设备列表失败"
    -1312: "新增设备失败"
    -1313: "删除设备失败"
    -1314: "更新设备失败"
    -1315: "根据Id查询设备失败"
    -1316: "获取房间树结构数据失败"
    -1317: "获取区域树结构数据失败"
    -1318: "获取设备详情失败"
    -1319: "更新设备详情失败"
    -1320: "应用到更多的设备失败"
    -1321: "应用到更多的房间失败"
    -1322: "应用到此间失败"


    #问答库错误码 -1220-1240
    -1220: "删除问答失败"
    -1221: "新增问答失败"
    -1222: "修改问答失败"
    -1223: "查询问答失败"

    #笔录模板错误码 1240-1260
    -1240: "查询笔录模板失败"
    -1241: "删除笔录模板失败"
    -1242: "查看笔录模板详情失败"
    -1243: "创建模板失败"
    -1244: "修改笔录模板失败"
